<#
.SYNOPSIS
    Run Consilium's processes at boot on Windows, restarted if they stop.

.DESCRIPTION
    The Windows counterpart of the systemd units in deploy/service/systemd/.

    Windows services must be written against the service control manager's
    API; python.exe is not one, and registering it with `sc.exe create` gives a
    service that Windows kills after 30 seconds (error 1053). The usual fix is a
    third-party wrapper executable, which is one more binary to vet and carry.
    This uses the Task Scheduler instead, which every supported Windows
    version has: one task per role, started at boot under a service account,
    restarted by the Task Scheduler if the process exits.

    Each task runs `winbench start` for one role, so winbench's own supervisor
    (winbench/winbench/procs.py) is what keeps the child processes alive. It
    puts them in a Job Object, so stopping the task stops the whole tree and
    leaves no orphan holding a database connection or a port.

      Consilium Web        winbench start --background-workers 0 --no-scheduler
      Consilium Workers    winbench start --web-workers 0 --no-scheduler --background-workers N
      Consilium Scheduler  winbench start --web-workers 0 --background-workers 0

    Exactly one scheduler across the whole deployment: register the scheduler
    task on one machine only (-NoScheduler on the others).

    NOT YET RUN ON WINDOWS. Written against the documented cmdlets; the first
    run on a real machine is part of the Windows acceptance script in
    docs/RUNBOOK.md.

.EXAMPLE
    # a group-managed service account (no password to manage)
    .\register-services.ps1 -InstallDir C:\consilium -Site governance.example.internal -UserId 'EXAMPLE\svc-consilium$'

.EXAMPLE
    # a local account; prompts for its password once
    .\register-services.ps1 -InstallDir C:\consilium -Site governance.example.internal -Credential (Get-Credential .\svc-consilium)
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $InstallDir,
    [Parameter(Mandatory)] [string] $Site,
    [string] $UserId = "",
    [pscredential] $Credential = $null,
    [int] $BackgroundWorkers = 2,
    [switch] $NoScheduler,
    [switch] $Unregister
)

$ErrorActionPreference = "Stop"
$python = Join-Path $InstallDir "env\Scripts\python.exe"
$tasks = [ordered]@{
    "Consilium Web"       = "start --site $Site --background-workers 0 --no-scheduler"
    "Consilium Workers"   = "start --site $Site --web-workers 0 --no-scheduler --background-workers $BackgroundWorkers"
    "Consilium Scheduler" = "start --site $Site --web-workers 0 --background-workers 0"
}
if ($NoScheduler) { $tasks.Remove("Consilium Scheduler") }

if ($Unregister) {
    foreach ($name in $tasks.Keys) {
        Unregister-ScheduledTask -TaskName $name -Confirm:$false -ErrorAction SilentlyContinue
        Write-Host "  removed $name"
    }
    return
}

if (-not (Test-Path $python)) { throw "no Python environment at $python; install first" }

# Restart whenever the process exits, forever, a minute apart; never time out;
# never start a second copy.
$settings = New-ScheduledTaskSettingsSet `
    -RestartCount 9999 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable

$trigger = New-ScheduledTaskTrigger -AtStartup

foreach ($name in $tasks.Keys) {
    $action = New-ScheduledTaskAction -Execute $python `
        -Argument "-m winbench.cli $($tasks[$name])" -WorkingDirectory (Join-Path $InstallDir "sites")
    $register = @{ TaskName = $name; Action = $action; Trigger = $trigger; Settings = $settings; Force = $true
                   Description = "Consilium: $name. Generated by deploy/service/windows/register-services.ps1." }
    if ($Credential) {
        $register.User = $Credential.UserName
        $register.Password = $Credential.GetNetworkCredential().Password
        $register.RunLevel = "Limited"
    } elseif ($UserId) {
        # A group-managed service account: Windows fetches its password itself.
        $register.Principal = New-ScheduledTaskPrincipal -UserId $UserId -LogonType Password -RunLevel Limited
    } else {
        throw "pass -UserId (a group-managed service account) or -Credential (a local service account)"
    }
    Register-ScheduledTask @register | Out-Null
    Write-Host "  registered $name"
}

# FRAPPE_BENCH_ROOT is how winbench finds the installation when started from
# sites\; set it machine-wide for the service account's processes.
[Environment]::SetEnvironmentVariable("FRAPPE_BENCH_ROOT", $InstallDir, "Machine")

Write-Host "`nStart now with:  Get-ScheduledTask 'Consilium *' | Start-ScheduledTask"
