#!/usr/bin/env python3
"""Produce the third-party licence inventory.

A licence review is one of the things that stops enterprise software being
installed, and it is far cheaper to answer before it is asked. This reads the
metadata of every installed dependency, groups by licence family, and flags what
a reviewer will want to look at by hand.

    python scripts/license_report.py > docs/LICENSES.md

Two caveats, stated here because they matter more than the table:

  * Package metadata is self-declared and sometimes absent. A package reporting
    UNKNOWN usually has a licence file that simply is not in its metadata — the
    framework itself is one — so UNKNOWN means "read the file", not "no licence".

  * This is an inventory, not advice. Whether a given licence is acceptable is a
    decision for the organisation's own review, and this exists to give that
    review something accurate to work from.
"""

from __future__ import annotations

import importlib.metadata as md
import re
import sys
from collections import defaultdict

# Ordered: the first pattern that matches wins, so the copyleft families are
# tested before the permissive ones they sometimes name in the same string.
FAMILIES = [
    ("AGPL", r"\bAGPL|Affero"),
    # LGPL before GPL, deliberately. "GNU Library or Lesser General Public
    # License" contains "General Public License", so a GPL pattern tested first
    # claims it and reports weak copyleft as strong.
    ("LGPL", r"\bLGPL|Lesser General|Library or Lesser"),
    ("GPL", r"\bGPL|General Public License"),
    ("MPL", r"\bMPL|Mozilla"),
    ("Apache", r"Apache"),
    ("MIT", r"\bMIT\b"),
    ("BSD", r"\bBSD\b"),
    ("ISC", r"\bISC\b"),
    ("PSF", r"Python Software Foundation|\bPSF\b"),
    ("Zope", r"Zope|\bZPL\b"),
    ("Public domain", r"Unlicense|public domain|CC0"),
]

# What a reviewer needs to know about each family, in one line.
NOTES = {
    "AGPL": "Treats use over a network as distribution. **Nothing here uses it.**",
    "GPL": "Strong copyleft. Obligations attach on distribution.",
    "LGPL": "Weak copyleft. Used as a library, obligations attach on distribution, not on use.",
    "MPL": "File-level copyleft. Obligations attach to modified files, on distribution.",
    "Apache": "Permissive, with an express patent grant.",
    "MIT": "Permissive.",
    "BSD": "Permissive.",
    "ISC": "Permissive.",
    "PSF": "Permissive.",
    "Zope": "Permissive, BSD-like.",
    "Public domain": "No conditions.",
    "Unclassified": "Read the package's own licence file. Absent metadata is common and is not the same as no licence.",
}


# Where a package offers a choice, the recipient elects — so the family is the
# least restrictive option on offer, not the first one listed.
PERMISSIVENESS = ["Public domain", "MIT", "BSD", "ISC", "PSF", "Zope", "Apache",
                  "MPL", "LGPL", "GPL", "AGPL", "Unclassified"]


def family(text: str) -> str:
    text = (text or "").strip()
    if not text or text.upper() in {"UNKNOWN", "NONE"}:
        return "Unclassified"
    options = [part.strip() for part in re.split(r"\bOR\b", text)] if " OR " in text else [text]
    found = set()
    for option in options:
        for name, pattern in FAMILIES:
            if re.search(pattern, option, re.I):
                found.add(name)
                break
    if not found:
        return "Unclassified"
    return min(found, key=PERMISSIVENESS.index)


def declared(dist) -> str:
    meta = dist.metadata
    explicit = meta.get("License")
    if explicit and explicit.strip() and explicit.strip().upper() != "UNKNOWN":
        return explicit.strip().splitlines()[0][:70]
    # All of them, not the first. A package offering a choice of licences —
    # pyphen offers GPL, LGPL or MPL — reads as its most restrictive option if
    # only the first classifier is shown, and the recipient's election is
    # exactly the fact a reviewer needs.
    classifiers = [
        c.split("::")[-1].strip()
        for c in (meta.get_all("Classifier") or [])
        if c.startswith("License ::")
    ]
    if classifiers:
        return " OR ".join(classifiers)
    for key in ("License-Expression", "License-File"):
        value = meta.get(key)
        if value:
            return str(value).strip()
    return "UNKNOWN"


def main() -> int:
    packages = []
    for dist in md.distributions():
        name = dist.metadata.get("Name")
        if not name:
            continue
        licence = declared(dist)
        packages.append((name, dist.version, licence, family(licence)))

    packages.sort(key=lambda p: p[0].lower())
    by_family: dict[str, list] = defaultdict(list)
    for entry in packages:
        by_family[entry[3]].append(entry)

    print("# Third-party licences\n")
    print("Generated by `scripts/license_report.py` from the metadata of every")
    print("installed dependency. Regenerate it whenever the dependency set changes.\n")
    print("**This is an inventory, not advice.** Whether a licence is acceptable is a")
    print("decision for your own review; this exists so that review has something")
    print("accurate to work from.\n")

    print("## Summary\n")
    print("| Licence family | Packages | What it means |")
    print("|---|---:|---|")
    order = ["AGPL", "GPL", "LGPL", "MPL", "Apache", "MIT", "BSD", "ISC", "PSF",
             "Zope", "Public domain", "Unclassified"]
    for name in order:
        rows = by_family.get(name)
        if not rows and name != "AGPL":
            continue
        print(f"| {name} | {len(rows or [])} | {NOTES[name]} |")

    print(f"\n**Total: {len(packages)} packages.**\n")

    copyleft = [e for n in ("AGPL", "GPL", "LGPL", "MPL") for e in by_family.get(n, [])]
    unclassified = by_family.get("Unclassified", [])

    print("## Everything that is not permissive\n")
    if copyleft:
        print("| Package | Version | Declared licence | Family |")
        print("|---|---|---|---|")
        for name, version, licence, fam in sorted(copyleft, key=lambda e: e[0].lower()):
            print(f"| `{name}` | {version} | {licence} | {fam} |")
    else:
        print("Nothing. Every dependency is permissively licensed.")
    print()

    if unclassified:
        print("## Packages whose metadata declares no licence\n")
        print("Absent metadata is common and does not mean absent licence. Each of")
        print("these has a licence file in its own distribution; read it there.\n")
        print("| Package | Version |")
        print("|---|---|")
        for name, version, _, _ in sorted(unclassified, key=lambda e: e[0].lower()):
            print(f"| `{name}` | {version} |")
        print()

    print("## Full inventory\n")
    print("| Package | Version | Declared licence |")
    print("|---|---|---|")
    for name, version, licence, _ in packages:
        print(f"| `{name}` | {version} | {licence} |")

    return 0


if __name__ == "__main__":
    sys.exit(main())
